<a href="https://colab.research.google.com/github/vkekd25/Project_Electronic_Commerce/blob/main/n221-decision-trees/n221a-decision-trees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="right" src="https://ds-cs-images.s3.ap-northeast-2.amazonaws.com/Codestates_Fulllogo_Color.png" width=100>

## *AIB / SECTION 2 / SPRINT 2 / NOTE 1*

# 📝 Assignment
---

# Decision Trees(결정트리)

## 캐글 인클래스(InClass) Competitions

### 1) 대회 참여(Join) 및 데이터셋 준비

- [캐글 계정을 만드세요](https://www.kaggle.com/), 공유된 인클래스 대회 url을 통해 이동한 후 대회에 참여하세요.
- H1N1 데이터를 훈련/검증/테스트 셋으로 나누어 준비하세요
- **(Urclass Quiz) 훈련데이터셋을 사용해 H1N1 타겟으로 기준모델을 설정하세요. 기준모델의 정확도를 제출하세요.**
    1. 0.24
    2. 0.50
    3. 0.76
    4. 1

In [19]:
train.head(3)

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,...,census_region,census_msa,n_adult_r,household_children,n_people_r,employment_industry,employment_occupation,hhs_region,state,vacc_h1n1_f
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,4,"MSA, Not Principle City",2.0,3.0,5.0,NaN,NaN,9,CALIFORNIA,0
1,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,2,"MSA, Principle City",1.0,0.0,1.0,Accommodation and Food Services Industries,Food Preparation and Serving Related Occupations,7,NEBRASKA,0
2,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1,"MSA, Not Principle City",1.0,2.0,3.0,Transportation and Warehousing Industries,Transportation and Material Moving Occupations,1,MASSACHUSETTS,0

#**데이터**  
**표적(Target)** 

vacc_h1n1_f - 응답자가 H1N1 독감 백신을 받았는지 여부. (이것은 당신이 경쟁을 위해 예측해야 하는 목표입니다)  
vacc_seas_f - 응답자가 계절성 독감 백신을 받았는지 여부.  
**특징(Features)**  
모든 이진 변수의 경우: 0 = 아니오; 1 = 예.  
* h1n1_concern - H1N1 독감에 대한 우려수준입니다. 
* 0 = 전혀 관련되지 않음; 1 = 별로 걱정하지 않음; 2 = 다소 우려됨; 3 = 매우 우려함. 
* h1n1_knowledge - H1N1 독감에 대한 지식 수준입니다.  
* 0 = 지식 없음; 1 = 약간의 지식; 2 = 많은 지식.   

behavioral_antiviral_meds - 항바이러스제를 복용했습니다. (바이너리)  
behavioral_avoidance - 독감과 유사한 증상이 있는 다른 사람과의 긴밀한 접촉을 피했습니다.(바이너리)  
behavioral_face_mask - 안면 마스크를 구입했습니다. (바이너리)  
behavioral_wash_hands - 손을 자주 씻거나 손 소독제를 사용했습니다. (바이너리)  
behavioral_large_gatherings - 대규모 모임에서 시간을 단축했습니다. (바이너리)  
behavioral_outside_home - 가족 이외의 사람들과의 접촉이 줄었습니다. (바이너리)  
behavioral_touch_face - 눈, 코 또는 입을 만지는 것을 피했습니다. (바이너리)  
Doctor_recc_h1n1 - 의사가 H1N1 독감 백신을 권장했습니다. (바이너리)  
Doctor_recc_seasonal - 의사가 계절성 독감 백신을 권장했습니다. (바이너리)  
만성 질환 - 다음과 같은 만성 질환이 있는 경우: 천식 또는 기타 폐 질환, 당뇨병, 심장 질환, 신장 질환, 겸상적혈구 빈혈 또는 기타 빈혈, 신경계 또는 신경근 질환, 간 질환 또는 면역 체계 약화 만성 질환이나 만성 질환을 위해 복용하는 약으로 인해 발생합니다. (바이너리)  
child_under_6_months - 6개월 미만의 어린이와 정기적으로 긴밀한 접촉을 합니다. (바이너리)  
health_insurance - 건강 보험이 있습니다. (바이너리)  
health_worker - 의료 종사자입니다. (바이너리)  

comment_h1n1_vacc_effective - H1N1 백신 효과에 대한 응답자의 의견. 전혀 효과적이지 않습니다. 그다지 효과적이지 않습니다. 모르겠어; 다소 효과적입니다. 매우 효과적  

comment_h1n1_risk - 백신 없이 H1N1 독감에 걸릴 위험에 대한 응답자의 의견. 매우 낮은; 다소 낮은; 모르겠어; 다소 높음; 매우 높음  
comment_h1n1_sick_from_vacc - 응답자의 H1N1 백신 접종으로 인한 질병에 대한 걱정. 전혀 걱정하지 않습니다. 별로 걱정하지 않습니다. 모르겠어; 약간 걱정됨; 매우 걱정  
comment_seas_vacc_effective - 계절 독감 백신 효과에 대한 응답자의 의견. 전혀 효과적이지 않습니다. 그다지 효과적이지 않습니다. 모르겠어; 다소 효과적입니다. 매우 효과적  
comment_seas_risk - 백신 없이 계절성 독감에 걸릴 위험에 대한 응답자의 의견. 매우 낮은; 다소 낮은; 모르겠어; 다소 높음; 매우 높음  
comment_seas_sick_from_vacc - 응답자가 계절 독감 백신을 맞아서 아플까봐 걱정합니다. 전혀 걱정하지 않습니다. 별로 걱정하지 않습니다. 모르겠어; 약간 걱정됨; 매우 걱정  
agegrp - 응답자의 연령 그룹입니다. 6개월 - 9세 10 - 17세; 18 - 34세; 35 - 44세; 45 - 54세; 55 - 64세; 65세 이상  
Education_comp - 자체 보고된 교육 수준.  
1 = < 12년; 2 = 12년; 3 = 일부 대학; 4 = 대학 졸업자  
raceeth4_i - 응답자의 인종.  
1 = 히스패닉; 2 = 비히스패닉, 흑인 전용 3 = 비-히스패닉, 백인 전용; 4 = 비히스패닉, 기타 또는 여러 인종  
sex_i - 응답자의 성별.  
1 = 남성 2 = 여성 2  
inc_pov - 2008년 인구 조사 빈곤 임계값에 대한 응답자의 가구 연간 소득.  
1 = > $75,000; 2 = <= $75,000; 3 = 빈곤 이하; 4 = 알 수 없음  
결혼 - 응답자의 결혼 상태.  
1 = 기혼 2 = 미혼  
rent_own_r - 응답자의 주택 상황.  
1 = 주택 소유; 2 = 주택 임대 또는 기타 계약  
고용_상태 - 응답자의 고용 상태입니다.  
고용; 노동력이 아닙니다. 한가한  
census_region - 실제 인구 조사 거주 지역(1=북동쪽, 2=중서부, 3=남쪽, 4=서쪽)  
census_msa - 미국 인구조사에서 정의한 대도시 통계 지역(MSA) 내의 응답자 거주지.  
n_adult_r - 가족의 다른 성인 수.  
house_children - 가구의 자녀 수입니다.  
n_people_r - 가구의 성인 수.  
고용_산업 - 응답자가 고용된 산업 유형입니다.  
고용_직업 - 응답자의 직업 유형. 값은 짧은 임의의 문자열로 표시됩니다.  
hhs_region - HHS 감시 지역 번호  
지역 1: CT,ME,MA,NH,RI,VT  
지역 2: 뉴저지,뉴욕  
지역 3: DE,DC,MD,PA,VA,WV  
지역 4: AL,FL,GA,KY,MS,NC,SC,TN  
지역 5: IL,IN,MI,MN,OH,WI  
지역 6: AR,LA,NM,OK,TX  
지역 7: IA,KS,MO,NE  
지역 8: CO,MT,ND,SD,UT,WY  
지역 10: AK,ID,OR,WA  
주 - 거주 주

In [ ]:
!pip install category_encoders
!pip install pandas-profiling==3.1.0

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
target = 'vacc_h1n1_f'
# target = 'vacc_seas_f'
train = pd.merge(pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/vacc_flu/train.csv'), 
                 pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/vacc_flu/train_labels.csv')[target], left_index=True, right_index=True)
test = pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/vacc_flu/test.csv')
sample_submission = pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/vacc_flu/submission.csv')

In [ ]:
#train = train.dropna(thresh = 20, axis = 0)

In [4]:
X = train.drop(columns = target)
y = train[target]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, train_size=0.8, random_state= 30)

In [5]:
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((33723, 38), (8431, 38), (33723,), (8431,))

In [8]:
from sklearn.tree import DecisionTreeClassifier
from category_encoders import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline


pipe = make_pipeline(
    OneHotEncoder(use_cat_names=True),  
    SimpleImputer(), 
    DecisionTreeClassifier(random_state=42, criterion='entropy')
)

pipe.fit(X_train, y_train)
print('훈련 정확도: ', pipe.score(X_train, y_train))
print('검증 정확도: ', pipe.score(X_val, y_val))

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

훈련 정확도:  0.990837114135753
검증 정확도:  0.7559008421302337

In [13]:
X_train

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,...,employment_status,census_region,census_msa,n_adult_r,household_children,n_people_r,employment_industry,employment_occupation,hhs_region,state
24381,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,...,Employed,4,"MSA, Not Principle City",1.0,0.0,1.0,Retail Trade Industries,Business and Financial Operations Occupations,9,HAWAII
24145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,2,"MSA, Principle City",2.0,1.0,3.0,NaN,NaN,5,WISCONSIN
9126,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,...,Employed,2,"MSA, Not Principle City",1.0,1.0,2.0,Public Administration Industries,Business and Financial Operations Occupations,7,NEBRASKA
35570,2.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,...,Not in Labor Force,3,"MSA, Principle City",1.0,0.0,1.0,NaN,NaN,3,DISTRICTOF COLUMBIA
13407,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN,...,Employed,1,Non-MSA,1.0,0.0,1.0,Accommodation and Food Services Industries,Food Preparation and Serving Related Occupations,1,NEW HAMPSHIRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30517,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,...,Not in Labor Force,3,"MSA, Principle City",1.0,0.0,1.0,NaN,NaN,6,TEXAS
919,3.0,2.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,Not in Labor Force,4,"MSA, Principle City",2.0,0.0,2.0,NaN,NaN,8,MONTANA
33268,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,...,Employed,3,Non-MSA,2.0,1.0,3.0,Retail Trade Industries,Sales and Related Occupations,4,TENNESSEE
4517,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,Not in Labor Force,2,"MSA, Principle City",1.0,0.0,1.0,NaN,NaN,5,INDIANA
38693,2.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,Not in Labor Force,2,Non-MSA,2.0,0.0,2.0,NaN,NaN,7,KANSAS

In [9]:
train.head(3)

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,...,census_region,census_msa,n_adult_r,household_children,n_people_r,employment_industry,employment_occupation,hhs_region,state,vacc_h1n1_f
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,4,"MSA, Not Principle City",2.0,3.0,5.0,NaN,NaN,9,CALIFORNIA,0
1,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,2,"MSA, Principle City",1.0,0.0,1.0,Accommodation and Food Services Industries,Food Preparation and Serving Related Occupations,7,NEBRASKA,0
2,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1,"MSA, Not Principle City",1.0,2.0,3.0,Transportation and Warehousing Industries,Transportation and Material Moving Occupations,1,MASSACHUSETTS,0

In [ ]:
y_val.value_counts(normalize=True)

0    0.769778
1    0.230222
Name: vacc_h1n1_f, dtype: float64

### 2) 데이터 EDA 및 특성공학 수행
- profiling을 사용하여 데이터를 살펴보고, missing value, zeros, cardinarity 등을 확인하여 처리하세요.
- 본인만의 특성공학을 수행하세요.

In [ ]:
from pandas_profiling import ProfileReport
profile = ProfileReport(train, minimal=True).to_notebook_iframe()
# pr=train.profile_report()
# pr.to_file('./pr_report.html') #pr_report.html 파일로저장

In [ ]:
train.select_dtypes('float').head(20).T

In [ ]:
X_train.T.duplicated() #중복값이 없는거 확인!

h1n1_concern                   False
h1n1_knowledge                 False
behavioral_antiviral_meds      False
behavioral_avoidance           False
behavioral_face_mask           False
behavioral_wash_hands          False
behavioral_large_gatherings    False
behavioral_outside_home        False
behavioral_touch_face          False
doctor_recc_h1n1               False
doctor_recc_seasonal           False
chronic_med_condition          False
child_under_6_months           False
health_insurance               False
health_worker                  False
opinion_h1n1_vacc_effective    False
opinion_h1n1_risk              False
opinion_h1n1_sick_from_vacc    False
opinion_seas_vacc_effective    False
opinion_seas_risk              False
opinion_seas_sick_from_vacc    False
agegrp                         False
education_comp                 False
raceeth4_i                     False
sex_i                          False
inc_pov                        False
marital                        False
rent_own_r                     False
employment_status              False
census_region                  False
census_msa                     False
n_adult_r                      False
household_children             False
n_people_r                     False
employment_industry            False
employment_occupation          False
hhs_region                     False
state                          False
dtype: bool

In [ ]:
train.describe(exclude='number').T.sort_values(by = 'unique')

,count,unique,top,freq
employment_status,31876,3,Employed,17173
census_msa,42154,3,"MSA, Not Principle City",18957
opinion_h1n1_vacc_effective,33375,6,Somewhat Effective,14729
opinion_h1n1_risk,33329,6,Somewhat Low,12520
opinion_h1n1_sick_from_vacc,33285,6,Not Very Worried,11582
opinion_seas_vacc_effective,33220,6,Somewhat Effective,14543
opinion_seas_risk,33153,6,Somewhat Low,11397
opinion_seas_sick_from_vacc,33089,6,Not At All Worried,14749
agegrp,42154,7,65+ Years,8517
employment_industry,17165,23,Health Care and Social Assistance Industries,3086
employment_occupation,17165,25,Management Occupations,2188
state,42154,51,NEW MEXICO,1017

In [5]:
import numpy as np

def engineer(df):
    """특성을 엔지니어링 하는 함수입니다."""
    
    # 높은 카디널리티를 가지는 특성을 제거합니다.
    selected_cols = df.select_dtypes(include=['number', 'object'])
    labels = selected_cols.nunique() # 특성별 카디널리티 리스트
    selected_features = labels[labels <= 30].index.tolist() # 카디널리티가 30보다 작은 특성만 선택합니다.
    df = df[selected_features]
    
    # 새로운 특성을 생성합니다.
    behaviorals = [col for col in df.columns if 'behavioral' in col] 
    df['behaviorals'] = df[behaviorals].sum(axis=1)
    
    
    dels = [col for col in df.columns if ('employment' in col or 'seas' in col)]
    df.drop(columns=dels, inplace=True)
        
    return df

In [ ]:
train.head()

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,...,census_region,census_msa,n_adult_r,household_children,n_people_r,employment_industry,employment_occupation,hhs_region,state,vacc_h1n1_f
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,4,"MSA, Not Principle City",2.0,3.0,5.0,NaN,NaN,9,CALIFORNIA,0
1,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,2,"MSA, Principle City",1.0,0.0,1.0,Accommodation and Food Services Industries,Food Preparation and Serving Related Occupations,7,NEBRASKA,0
2,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1,"MSA, Not Principle City",1.0,2.0,3.0,Transportation and Warehousing Industries,Transportation and Material Moving Occupations,1,MASSACHUSETTS,0
3,2.0,2.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,3,"MSA, Not Principle City",2.0,2.0,4.0,"Professional, Scientific, and Technical Servic...",Legal Occupations,6,LOUISIANA,0
4,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,3,"MSA, Not Principle City",3.0,0.0,3.0,Education Services Industries,Office and Administrative Support Occupations,4,ALABAMA,1

In [6]:
X_train = engineer(X_train)
X_val = engineer(X_val)
test = engineer(test)

In [ ]:
X_train.select_dtypes('float').head(20).T

,24381,24145,9126,35570,13407,22691,40026,28112,21852,13470,1160,23367,37249,31049,33745,24418,37869,18826,2089,23639
h1n1_concern,1.0,NaN,3.0,2.0,1.0,NaN,NaN,1.0,2.0,1.0,NaN,1.0,2.0,NaN,2.0,NaN,0.0,2.0,1.0,3.0
h1n1_knowledge,1.0,NaN,1.0,2.0,2.0,NaN,NaN,2.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,NaN,2.0,2.0,2.0,0.0
behavioral_antiviral_meds,0.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,NaN,1.0,NaN,0.0,0.0,0.0,0.0
behavioral_avoidance,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,0.0,0.0,NaN,1.0,0.0,NaN,0.0,NaN,1.0,1.0,1.0,1.0
behavioral_face_mask,0.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,NaN,1.0,NaN,0.0,0.0,1.0,0.0
behavioral_wash_hands,0.0,NaN,1.0,1.0,1.0,NaN,NaN,1.0,0.0,1.0,NaN,1.0,0.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0
behavioral_large_gatherings,0.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,1.0,0.0,NaN,1.0,NaN,1.0,0.0,1.0,0.0
behavioral_outside_home,0.0,NaN,0.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,1.0,0.0,NaN,1.0,NaN,1.0,0.0,0.0,0.0
behavioral_touch_face,0.0,NaN,1.0,1.0,0.0,NaN,NaN,1.0,1.0,0.0,NaN,1.0,0.0,NaN,0.0,NaN,1.0,1.0,1.0,1.0
doctor_recc_h1n1,1.0,1.0,1.0,1.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN
chronic_med_condition,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
child_under_6_months,0.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,1.0,0.0,0.0,1.0
health_insurance,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,1.0,1.0,NaN
health_worker,0.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,0.0,1.0,0.0
education_comp,4.0,NaN,3.0,3.0,3.0,NaN,NaN,4.0,1.0,2.0,NaN,1.0,3.0,NaN,2.0,NaN,3.0,4.0,4.0,2.0
marital,2.0,NaN,2.0,2.0,2.0,NaN,NaN,1.0,2.0,2.0,NaN,2.0,1.0,NaN,2.0,NaN,1.0,1.0,1.0,2.0
rent_own_r,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0
n_adult_r,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0
household_children,0.0,1.0,1.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,2.0,3.0,2.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0
n_people_r,1.0,3.0,2.0,1.0,1.0,4.0,4.0,3.0,2.0,1.0,4.0,5.0,4.0,3.0,2.0,3.0,2.0,5.0,2.0,1.0
behaviorals,0.0,0.0,3.0,4.0,2.0,0.0,0.0,3.0,1.0,1.0,0.0,5.0,0.0,0.0,5.0,0.0,5.0,3.0,5.0,3.0


### 3) 모델링 수행
- 결정트리를 학습시킵니다. 하이퍼파라미터를 수정하여 성능을 높여보세요. 과적합을 주의하세요!
- 검증세트 스코어를 확인하세요.(평가지표는 F1-score입니다, 수식은 캐글 Overview-Evaluation 페이지를 확인해 주세요. 평가지표에 대한 내용은 다음에 자세히 배우고 활용할 것입니다 지금은 스코어를 올리기 위한 노력을 전혀 기울이지 말고 결정트리의 개념과 코드이해, 사용에 집중하세요!)
- 특성중요도를 그래프로 나타내 보세요
- **(Urclass Quiz) 검증세트의 F1-score를 제출하세요. (0.5 이상 통과)**

In [9]:
pipe = make_pipeline(
    OneHotEncoder(use_cat_names=True), 
    SimpleImputer(missing_values=np.nan, strategy='mean'), 
    DecisionTreeClassifier(min_samples_leaf=8, max_depth = 8, random_state=30, criterion='gini')
)

pipe.fit(X_train, y_train)
print('훈련 정확도', pipe.score(X_train, y_train))
print('검증 정확도', pipe.score(X_val, y_val))

# Val f1_score
from sklearn.metrics import f1_score
y_pred = pipe.predict(X_val)
f1 = f1_score(y_val, y_pred)
print('Val f1 score :',f1)

훈련 정확도 0.8345046407496367
검증 정확도 0.8278970466136876
Val f1 score : 0.5721026245945149

In [ ]:
import graphviz
from sklearn.tree import export_graphviz

model_dt = pipe.named_steps['decisiontreeclassifier']
enc = pipe.named_steps['onehotencoder']
encoded_columns = enc.transform(X_val).columns

dot_data = export_graphviz(model_dt
                          , max_depth=7
                          , feature_names=encoded_columns
                          , class_names=['no', 'yes']
                          , filled=True
                          , proportion=True)
display(graphviz.Source(dot_data))

In [11]:
model_dt = pipe.named_steps['decisiontreeclassifier']

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline 
plt.rcParams.update({'figure.max_open_warning': 0})
importances = pd.Series(model_dt.feature_importances_, encoded_columns)
plt.figure(figsize=(10,13))
importances.sort_values().plot.barh();

### 4) 테스트셋 예측 결과 제출(Submission)

- 테스트셋에 대한 예측 결과를 캐글에 제출 하세요.(스코어가 많이 낮게 나와도 결정트리를 잘 이해하고 결과를 내었다면 충분합니다!)
- **(Urclass Quiz) 캐글 Leaderboard의 본인 Score를 제출하세요.**

In [13]:
# print('훈련 정확도', pipe.score(X_train, y_train))
# print('검증 정확도', pipe.score(X_val, y_val))
y_pred = pipe.predict(test)
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
y_train.shape

In [14]:
sample_submission['vacc_h1n1_f'] = y_pred
sample_submission['vacc_h1n1_f']

0        0
1        0
2        0
3        0
4        0
        ..
28099    0
28100    0
28101    0
28102    1
28103    0
Name: vacc_h1n1_f, Length: 28104, dtype: int64

In [ ]:
y_pred[:20]

In [15]:
sample_submission.to_csv(r'H1N1_submission.csv', index=False)

## 🔥 도전과제(Github - Discussion)

### 4) 2개 이상의 imputer를 사용해 각각 특성-타겟 관계 그래프를 그려 공유하고 다음 질문에 대해 서로 논의해 보세요. 
- scikit-learn imputer([scikit-learn imputers](https://scikit-learn.org/stable/modules/impute.html))
- seaborn plots 사용하여 관심있는 특성들과 target간의 관계를 그래프로 나타내 보세요.
- 사용하신 imputer는 각각 어떤 장단점을 갖고 있으며 어떤 상황에서 사용하면 좋을까요? 
- 만드신 특성-타겟 관계 그래프에서 차이점이 있다면 무엇이고, 왜 그런 차이가 발생했다고 생각하시나요? 
- [Seaborn "Categorical estimate" plots](https://seaborn.pydata.org/tutorial/categorical.html)
- [Seaborn linear model plots](https://seaborn.pydata.org/tutorial/regression.html)

**Simple Imputer**  
:결측값을 대입하기 위한 기본 전략을 제공한다. 결측값은 제공된 상수 값으로 대치되거나 결측값이 있는 각 열의 통계(mean, median, most_frequent)를 사용하여 대치될 수 있다.

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.metrics import f1_score
import numpy as np

pipe = make_pipeline(
    OneHotEncoder(use_cat_names=True), 
    SimpleImputer(missing_values = np.nan, strategy = 'mean'), # missing_values 열의 평균값을 대체하는 방법을 보여준다. default값
    DecisionTreeClassifier(min_samples_leaf=8, max_depth = 8, random_state=30, criterion='gini')
)

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_val)
f1 = f1_score(y_val, y_pred) # Val f1_score
print('훈련 정확도', pipe.score(X_train, y_train))
print('검증 정확도', pipe.score(X_val, y_val))
print('Val f1 score :',f1)

**Iterative Imputer**   
: 다른 모든 것에서 각 특성을 추정하는 다변수 대입기. 라운드 로빈 방식으로 다른 기능의 함수로 결측값이 있는 각 기능을 모델링하여 결측값을 대치하는 전략입니다. 각 단계에서 기능 열은 출력으로 지정되고 y다른 기능 열은 입력으로 처리됩니다 X. 회귀자는 알려진 에 적합합니다 . 그런 다음 회귀자를 사용하여 의 결측값을 예측합니다 .

In [11]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.metrics import f1_score

pipe = make_pipeline(
    OneHotEncoder(use_cat_names=True), 
    IterativeImputer(max_iter=10, random_state=30), 
    # 이것은 반복적인 방식으로 각 기능에 대해 수행된 다음 대치 라운드에 대해 반복됩니다. 최종 전가 라운드의 결과가 반환됩니다.(X, y)yymax_iter
    DecisionTreeClassifier(min_samples_leaf=8, max_depth = 8, random_state=30, criterion='gini')
)

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_val)
f1 = f1_score(y_val, y_pred)
print('훈련 정확도', pipe.score(X_train, y_train))
print('검증 정확도', pipe.score(X_val, y_val))
print('Val f1 score :',f1)# Val f1_score

훈련 정확도 0.8349790943866204
검증 정확도 0.8315739532677026
Val f1 score : 0.5748502994011976

**KNN Imputer**  
:이 KNNImputer클래스는 k-최근접 이웃 접근 방식을 사용하여 결측값을 채우기 위한 전가를 제공합니다. 기본적으로 결측값을 지원하는 유클리드 거리 측정법이 nan_euclidean_distances가장 가까운 이웃을 찾는 데 사용됩니다.

In [16]:
from sklearn.impute import KNNImputer
from sklearn.metrics import f1_score

pipe = make_pipeline(
    OneHotEncoder(use_cat_names=True), 
    KNNImputer(n_neighbors=2, weights="uniform"), 
    #각 누락된 기능은 n_neighbors해당 기능에 대한 값이 있는 가장 가까운 이웃의 값을 사용하여 대치됩니다.
    #거리가 정의된 이웃이 하나 이상 있는 경우 나머지 이웃의 가중 또는 비가중 평균이 대치 중에 사용됩니다. 훈련에서 기능이 항상 누락된 경우 에서 제거됩니다
    DecisionTreeClassifier(min_samples_leaf=8, max_depth = 8, random_state=30, criterion='gini')
)

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_val)
f1 = f1_score(y_val, y_pred) # Val f1_score
print('훈련 정확도', pipe.score(X_train, y_train))
print('검증 정확도', pipe.score(X_val, y_val))
print('Val f1 score :',f1)

훈련 정확도 0.8224653797111764
검증 정확도 0.8159174475151227
Val f1 score : 0.5493612078977933